version: "3.9"

services:
  builder-materials-market-front:
    container_name: "${CONTAINER_NAME}"
    networks:
      - bmm_main_network
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env

networks:
  bmm_main_network:
    external: true
